services:
  db:
    image: postgres:16
    container_name: incomeexpense-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: incomeexpense
    networks:
      - app_network
      - proxy_net
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ${IMAGE_PREFIX}/backend:latest
    container_name: incomeexpense-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: incomeexpense
      JWT_SECRET: supersecret123
    networks:
      - app_network
      - proxy_net
  exporter:
    image: ${IMAGE_PREFIX}/exporter:latest
    container_name: incomeexpense-exporter
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: incomeexpense
      DB_USER: postgres
      DB_PASS: postgres
    networks:
      - app_network
      - proxy_net

  frontend:
    image: ${IMAGE_PREFIX}/frontend:latest
    container_name: incomeexpense-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "1292:80"
    networks:
      - app_network
      - proxy_net

networks:
  app_network:
    driver: bridge
  proxy_net:
    external: true
volumes:
  pgdata:
